# Runs eslint and jest tests on pushes.
name: CI Jest

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Runs ESlint and the Jest tests.
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Sets up Node.
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: clean install with NPM
        run: npm ci
      - name: Build the typescript
        run: npm run build
      - name: Run lints
        run: npm run lint
      - name: Run tests
        run: npm run test
